### ISSUE TITLE
这个目标语言现在感觉是最麻烦的步骤，如果能在结果栏中显示所有语言的翻译就好了

### ISSUE THREAD

**Issue by J1nVel** [N0I0C0K/PowerTranslator#14]
- 如果每个插件只能占用一个结果栏，那可以把所有语言的翻译放在同一行，这样省的每次翻译还得设置目标语言。
- 当然如果可以在程序中就自定义好经常用的语言就好了，然后再基于第一点，可用性和易用性会大大更加

**Comment by N0I0C0K** [comment]
确实是这样，默认翻译的语言是英文和中文的互译，如果需要翻译为其他语言的话就需要指定语言。之前就想加入“默认翻译语言”，一直没有上的原因是Powertoys提供的自定义设置只有bool类型，但是我会在后续版本尝试加入此功能。

**Comment by N0I0C0K** [comment]
此功能以上线，感谢提交改进建议！
