### ISSUE TITLE
powerToys 升级到 v0.72.0 后加载不了插件了

### ISSUE THREAD

**Issue by hepeng10** [N0I0C0K/PowerTranslator#17]
powerToys 自动更新到 v0.72.0，插件加载不了了呢

**Comment by N0I0C0K** [comment]
收到，晚上回去验证解决

**Comment by blandcoder** [comment]
powertoys V0.72.0目录结构改变了，没有找到Modules/Launcher/Plugins  文件夹

**Comment by N0I0C0K** [comment]
## 解决方案
因为官方更新了，新的Plugin目录路径为`{PowerToys install path}\RunPlugins`，比如我的就是`C:\Program Files\PowerToys\RunPlugins`，重新解压到这个目录下就行

![image](https://github.com/N0I0C0K/PowerTranslator/assets/30338746/dc1ba915-f3c2-4b35-ab84-daf1221982f4)
