### ISSUE TITLE
卡在Initializing...

### ISSUE THREAD

**Issue by Huckies** [N0I0C0K/PowerTranslator#19]
Powertoys版本0.73.0

尝试的解决方法

- 重启powertoys
- 重启电脑
- 重新安装本插件
- 更换网络连接方式

均无效，在Initializing时按ctrl+enter可以正常发声朗读

**Comment by N0I0C0K** [comment]
Hi！已经注意到这个问题了，目前已经确定了问题是：
1. 有一个接口发生了错误
2. 接口的切换逻辑出现了一定的问题

已经在修复过程中了！

**Comment by N0I0C0K** [comment]
Hi！在最新的release中已经修复了这个问题，升级即可修复！
