### ISSUE TITLE
有计划添加支持微软翻译吗？

### ISSUE THREAD

**Issue by yinleiCoder** [N0I0C0K/PowerTranslator#20]
微软翻译的结果比较不错，像沉浸式翻译插件添加了多个翻译引擎，用了这么多个，感觉微软翻译不错

**Comment by N0I0C0K** [comment]
是有计划添加其他翻译引擎，包括
- google
- 微软翻译

最近比较忙，我会尽快添加上🫡

**Comment by yinleiCoder** [comment]
感谢你的付出，翻译功能确实很有用，mac上有raycast和alfred，powertoys终于看到了这款插件
