### ISSUE TITLE
設定裡沒有目標語言

### ISSUE THREAD

**Issue by DonkeyBear** [N0I0C0K/PowerTranslator#23]
我看了一下 commit 紀錄，這個 feature 應該沒有改掉，但是我在 PowerToys Run 的設定下沒有看到目標語言的設定選項，希望作者能夠協助解決這個問題，因為我實在不想每次翻譯都輸入 `->zh-CHT`（竟然還 case-sensitive），感謝。

**Comment by N0I0C0K** [comment]
Hi！這個feature將會在下一次release正式發佈，但是我可以現在打包一份給你
[Translator.zip](https://github.com/N0I0C0K/PowerTranslator/files/13233701/Translator.zip)

**Comment by DonkeyBear** [comment]
感謝你的光速回覆，比我更新都快，不過我使用附件的版本仍然無法設定目標語言，不知道是不是我這邊的問題？

**Comment by N0I0C0K** [comment]
PowerToys v0.75後特殊選項的UI有一定問題，官方應該還在修復

**Comment by DonkeyBear** [comment]
了解，那我這個 issue 就先開著讓其他有相同問題的人看，等解決了會再回來關掉 👍

**Comment by Edemilorhea** [comment]
請問現在這個包，也能申請一份嗎，我也是想要直接設定成繁中

**Comment by N0I0C0K** [comment]
> 請問現在這個包，也能申請一份嗎，我也是想要直接設定成繁中

目前v0.75版本切換默認語言的UI展示有一些問題，等待官方修復中😶‍🌫️

**Comment by N0I0C0K** [comment]
“默認翻譯目標語言”選項失效問題已經修復🫡
