### ISSUE TITLE
有些翻译莫名其妙，让人摸不着头脑。

### ISSUE THREAD

**Issue by flyinke** [N0I0C0K/PowerTranslator#24]
![image](https://github.com/N0I0C0K/PowerTranslator/assets/16532650/88e72cff-4bf9-4dd6-be1a-84ac2b9906ac)

**Comment by N0I0C0K** [comment]
![image](https://github.com/N0I0C0K/PowerTranslator/assets/30338746/10f7c9cc-1ce4-4691-b7c9-a84e6b59284c)

可以给出详细的信息吗，我无法复现😶‍🌫️。
你可以将鼠标移动到结果上查看更多信息

![image](https://github.com/N0I0C0K/PowerTranslator/assets/30338746/558f240c-85e8-4b18-94b2-3a259418f50e)

**Comment by flyinke** [comment]
![image](https://github.com/N0I0C0K/PowerTranslator/assets/16532650/cb54ddf0-ed75-4f7c-b8de-0511c5ceee1e)

**Comment by flyinke** [comment]
我又在我另一台电脑试了下，是正常的结果跟你一样。。。

**Comment by N0I0C0K** [comment]
接口返回的结果确实是“Zhong wanxie”，可能是有道翻译那边有点问题🫡，我会在下一次更新一下接口调度，减少备用接口的调用

**Comment by N0I0C0K** [comment]
新的版本已经发布，可以验证一下🫡
