### ISSUE TITLE
关于安装路径

### ISSUE THREAD

**Issue by SZ2528** [N0I0C0K/PowerTranslator#25]
在你的文档中关于安装插件是这么说的
> 解压到`{安装目录}\RunPlugins\`如图所示

我在[官方文档](https://github.com/microsoft/PowerToys/blob/main/doc/thirdPartyRunPlugins.md)中看到了这个
> The recommended path for the plugins is `%LOCALAPPDATA%\Microsoft\PowerToys\PowerToys Run\Plugins`.

这个路径进行文件操作不需要管理员权限，不会出现一些无法解压之类神奇的问题

所以可以改下文档罢

**Comment by N0I0C0K** [comment]
确实需要改一下文档，之前写文档的时候官方还没有正式提及第三方插件。感谢！

**Comment by N0I0C0K** [comment]
已修正🫡
