### ISSUE TITLE
PowerToys v 0.76.1上，图标无法正常显示的问题

### ISSUE THREAD

**Issue by radyyt** [N0I0C0K/PowerTranslator#28]
在PowerToys v 0.76.1上安装插件后，发现图标无法正常显示

![{434B099C-7932-425d-8D1E-6EA5D4A61176}](https://github.com/N0I0C0K/PowerTranslator/assets/67799862/320ed0b0-bc66-4677-9ed6-cbf07463be18)

**Comment by N0I0C0K** [comment]
对，升级0.76.0的时候我就发现了，我会尽快修复🫡

**Comment by N0I0C0K** [comment]
已修复，感谢提出问题🎈
