### ISSUE TITLE
拷贝进去无任何反应。

### ISSUE THREAD

**Issue by realpeter** [N0I0C0K/PowerTranslator#31]
C:\Users\Administrator\AppData\Local\Microsoft\PowerToys\PowerToys Run\Plugins没有自动调用插件，powertoys插件里面也看不到此插件。

**Comment by N0I0C0K** [comment]
仔细阅读[安装文档](https://github.com/N0I0C0K/PowerTranslator?tab=readme-ov-file#install)

确保解压后Plugins目录的结构是这样的
```
+---Plugins
|   \---Translator
|       |   plugin.json
|       |   Translator.dll
|       |
|       \---Images
|               history.dark.png
|               history.light.png
|               translator.dark.png
|               translator.light.png
```

**Comment by realpeter** [comment]
可以看到了这次，但是就算打开了，用您给的方法键入后没有翻译，也没有反应。



***@***.***
 
发件人： Nick
发送时间： 2023-12-19 17:30
收件人： N0I0C0K/PowerTranslator
抄送： realpeter; Author
主题： Re: [N0I0C0K/PowerTranslator] 拷贝进去无任何反应。 (Issue #31)
仔细阅读安装文档
确保解压后Plugins目录的结构是这样的
+---Plugins
|   \---Translator
|       |   plugin.json
|       |   Translator.dll
|       |
|       \---Images
|               history.dark.png
|               history.light.png
|               translator.dark.png
|               translator.light.png

**Comment by N0I0C0K** [comment]
检查插件是否已经开启，同时看一下触发关键字是什么（默认是|）

都没有问题的话键入"|hello"尝试一下

**Comment by realpeter** [comment]
我晕，没仔细看触发键换成了|，我还在一个劲的打^.感谢，非常感谢，辛苦了。学习了！
