### ISSUE TITLE
可以支持添加显示的语言吗？

### ISSUE THREAD

**Issue by Yueby** [N0I0C0K/PowerTranslator#33]
比如同时显示英语、日语、俄语的翻译结果。

**Comment by N0I0C0K** [comment]
这个不错！会在下一次更新添加🫡

**Comment by Yueby** [comment]
> 这个不错！会在下一次更新添加🫡

感谢大大！

**Comment by N0I0C0K** [comment]
Hi！更新已经上线[v0.10](https://github.com/N0I0C0K/PowerTranslator/releases/tag/v0.10)🫡
