### ISSUE TITLE
能否在单个英文单词查询的场景下展示音标？

### ISSUE THREAD

**Issue by sit-back-andrelax-plz** [N0I0C0K/PowerTranslator#34]
能否在单个英文单词查询的场景下展示音标？

**Comment by N0I0C0K** [comment]
是一个不错的提议🐱‍👓，会在下一个更新中添加

**Comment by N0I0C0K** [comment]
Hi！更新已经上线[v0.10](https://github.com/N0I0C0K/PowerTranslator/releases/tag/v0.10)🫡
