### ISSUE TITLE
当代理状态切换时，插件会失效

### ISSUE THREAD

**Issue by NaroZeol** [N0I0C0K/PowerTranslator#35]
有时当我关闭clash后，插件会失效，重启powertoys后恢复正常。
报错信息为：
由于目标计算机积极拒绝，无法连接。 (127.0.0.1:7890)

我不清楚这是clash的问题还是powertoys的问题。

**Comment by N0I0C0K** [comment]
是的，我也出现了这个问题。
具体的原因是：clash开启系统代理模式之后，C#的网络请求会自动使用这个系统代理，如果使用代理访问有道翻译服务就会出现服务拒绝。

后期我打算强制让网络不走代理试一下🫡

**Comment by NaroZeol** [comment]
好的，期待补丁的上线🥳

**Comment by N0I0C0K** [comment]
Hi！问题已经修复🫡  https://github.com/N0I0C0K/PowerTranslator/releases/tag/v0.10.1
