### ISSUE TITLE
能否添加一个打开词典网页的功能

### ISSUE THREAD

**Issue by NaroZeol** [N0I0C0K/PowerTranslator#39]
在使用时，受限于powertoys run的搜索框大小，有多个释义的词很容易显示不全。这时还要再去打开词典查询完整的翻译，感觉不是很方便。

如果能设置一个按钮跳转到对应的词典页面我觉得会很不错。

比如说输入hello，提供一个跳转到 https://dict.youdao.com/result?word=hello&lang=en 这个网页的方式。

**Comment by N0I0C0K** [comment]
建议很棒！会在下一个更新中添加

**Comment by NaroZeol** [comment]
感谢采纳！期待新功能的上线🥳🥳🥳

**Comment by N0I0C0K** [comment]
hi! 功能已经上线 https://github.com/N0I0C0K/PowerTranslator/releases/tag/v0.11.0

**Comment by NaroZeol** [comment]
感谢开发。
但是似乎最后呈现的功能和我想象中的不太一致。

我可能更需要的是一个直接跳转到查询词对应的词典界面，而不是查询结果对应的界面。
比如说在输入框中输入hello，我希望能够跳转到**hello**这个词对应的[界面](https://www.youdao.com/result?word=hello&lang=en)，而不是**你好 (nĭhăo)** 这个翻译结果对应的[界面](https://www.youdao.com/result?word=%E4%BD%A0%E5%A5%BD%20%28n%C4%ADh%C4%83o%29&lang=en)。

**Comment by N0I0C0K** [comment]
这就是为什么有一个选项用来展示原始查询
![image](https://github.com/N0I0C0K/PowerTranslator/assets/30338746/9f5acc9f-7038-4fd5-96db-acc99c4da4aa)
可以勾选这个选项，然后就可以看到原始查询了，就可以直接跳转了🫡

**Comment by N0I0C0K** [comment]
确实会稍微麻烦一点 😶‍🌫️

**Comment by NaroZeol** [comment]
抱歉没有考虑到这个选项。
虽然要将滚轮滑到最下面会有些麻烦，但这确实能实现我想要的功能👌

**Comment by N0I0C0K** [comment]
因为考虑到这个场景并不是很高频，所以会稍微麻烦一些，没有单独直接的入口

**Comment by NaroZeol** [comment]
嗯，我想这个issue可以关闭了
