### ISSUE TITLE
能写个选项将[query raw]这个关闭吗?

### ISSUE THREAD

**Issue by zhepamagod** [N0I0C0K/PowerTranslator#41]
每次翻译都有这行,不够简洁,也没什么用处.因为原始的输入在输入框中就能看到
所以能把这行注释了吗?或者添加一个选项可以关闭这行
res.Add(new ResultItem
  {
      Title = querySearch,
      SubTitle = "[query raw]"
  });

**Comment by N0I0C0K** [comment]
确实没什么用这个，当初是为了方便确认翻译结果是否和输入一样，现在看来没有这个必要了，下一个更新就取消掉这个

**Comment by N0I0C0K** [comment]
这里还有一个作用是对原始输入进行操作，比如我的意图就是输入 hello，然后去朗读这个单词。
还是决定开一个选项去选择是否取消更合适一点

**Comment by N0I0C0K** [comment]
hi, 已经更新了 https://github.com/N0I0C0K/PowerTranslator/releases/tag/v0.11.0

**Comment by zhepamagod** [comment]
6666
