### ISSUE TITLE
0.11 plugin.json 中的 Version 还是 0.9

### ISSUE THREAD

**Issue by kyan001** [N0I0C0K/PowerTranslator#43]
0.11 plugin.json 中的 Version 还是 0.9

https://github.com/N0I0C0K/PowerTranslator/blob/main/plugin.json

这里的 Version 需要更新吗？

**Comment by N0I0C0K** [comment]
确实，这里忘记改了😶‍🌫️

**Comment by N0I0C0K** [comment]
已经更新 🫡
